// Combine pipeline header+beauty grid with the LLM-curated places into the final app
// module src/data/cities/<id>.js.  Usage: node pipeline/assemble.mjs <cityId>
import { readFileSync, writeFileSync } from 'fs';

const id = process.argv[2];
const CONST = {
  nyc: 'NYC',
  sf: 'SF',
  boston: 'BOSTON',
  tokyo: 'TOKYO',
  paris: 'PARIS',
  london: 'LONDON',
  austin: 'AUSTIN',
  miami: 'MIAMI',
  chicago: 'CHICAGO',
  dc: 'DC',
}[id];
if (!CONST) {
  console.error('Unknown city');
  process.exit(1);
}

const base = JSON.parse(readFileSync(new URL(`./out/${id}.json`, import.meta.url)));
const places = JSON.parse(readFileSync(new URL(`./final/${id}-places.json`, import.meta.url)));

// strip pipeline-internal fields
for (const p of places) delete p._meta;

const city = {
  id: base.id,
  name: base.name,
  emoji: base.emoji,
  center: base.center,
  bbox: base.bbox,
  primaryZone: base.primaryZone,
  defaultStart: base.defaultStart,
  presets: base.presets,
  beauty: base.beauty,
  places,
};

const header = `// AUTO-GENERATED by the scenic pipeline (OSM + Wikipedia cross-reference + LLM blurbs).
// Regenerate: node pipeline/fetchOsm.mjs ${id} && node pipeline/fetchWiki.mjs ${id} && node pipeline/build.mjs ${id} && node pipeline/assemble.mjs ${id}
// Hand-edits will be overwritten.
`;
const body = `export const ${CONST} = ${JSON.stringify(city, null, 0)};\n`;
writeFileSync(new URL(`../src/data/cities/${id}.js`, import.meta.url), header + body);

const corr = places.filter((p) => p.corridor).length;
console.log(`${CONST}: wrote src/data/cities/${id}.js — ${places.length} places (${corr} corridors), beauty ${base.beauty.nx}x${base.beauty.ny}`);
