// Austin curation spec — see ../curate-lib.mjs. `src` ids come from out/austin.json.
import { curate } from '../curate-lib.mjs';

curate('austin', [
  // ---- Trail corridors ----
  {
    src: 'ann-roy-butler-hike-and-bike-trail-path',
    id: 'butler-hike-and-bike-trail',
    name: 'Ann and Roy Butler Hike-and-Bike Trail',
    category: 'waterfront',
    score: 5,
    blurb: 'Austin’s beloved 10-mile loop around the shores of Lady Bird Lake.',
    see: 'The downtown skyline mirrored in the water, paddleboarders and rowers, and the Pfluger and Lamar pedestrian bridges.',
    do: 'Run the full loop, crossing the lake on the boardwalk over the water on the south-east side.',
    tip: 'Shaded and crowded at dawn and dusk; the over-water boardwalk near I-35 is the highlight.',
    transit: 'Downtown Station (CapMetro Rail)',
    endpoint: true,
  },
  {
    src: 'barton-creek-greenbelt-violet-crown-trai-path',
    id: 'barton-creek-greenbelt',
    name: 'Barton Creek Greenbelt',
    category: 'path',
    score: 5,
    blurb: 'A rugged limestone creek trail winding into the green hills southwest of downtown.',
    see: 'Cliffs and swimming holes, cypress-shaded creek crossings, and rock climbers on the bluffs.',
    do: 'Run the Violet Crown Trail from Zilker out along the creek and back.',
    tip: 'Rooty and rocky — trail shoes help, and the creek can run high after rain.',
    transit: 'Zilker Park (CapMetro bus)',
    endpoint: true,
  },
  {
    src: 'shoal-creek-trail-path',
    id: 'shoal-creek-trail',
    name: 'Shoal Creek Trail',
    category: 'waterfront',
    score: 4,
    blurb: 'A creekside greenway running north from Lady Bird Lake through central Austin.',
    see: 'Limestone creek banks, Pease Park’s big oaks, and quiet stretches just blocks from downtown.',
    do: 'Link the lake trail with Pease Park on an out-and-back up the creek.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'waller-creek-greenbelt-trail-path',
    id: 'waller-creek-trail',
    name: 'Waller Creek Trail',
    category: 'waterfront',
    score: 3,
    blurb: 'A revitalized creek path threading the east side of downtown.',
    see: 'New creekside parks and boardwalks linking the Convention Center toward the lake.',
    do: null,
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'boggy-creek-greenbelt-trail-path',
    id: 'boggy-creek-greenbelt',
    name: 'Boggy Creek Greenbelt',
    category: 'path',
    score: 3,
    blurb: 'A green creekside corridor through historic East Austin.',
    see: 'Neighborhood gardens, ball fields, and shaded creek banks away from the crowds.',
    do: null,
    tip: null,
    transit: 'Plaza Saltillo (CapMetro Rail)',
  },
  {
    src: 'johnson-creek-hike-and-bike-trail-path',
    id: 'johnson-creek-trail',
    name: 'Johnson Creek Trail',
    category: 'path',
    score: 3,
    blurb: 'A short connector trail running up from the lake on the west side.',
    see: 'A leafy creek route linking the Butler trail toward the MoPac corridor.',
    do: 'Use it to extend the lake loop northwest.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'red-line-trail-path',
    id: 'red-line-trail',
    name: 'Red Line Trail',
    category: 'path',
    score: 3,
    blurb: 'An urban rail-trail shadowing the CapMetro Red Line east of downtown.',
    see: 'Murals and warehouses through the East Austin arts district.',
    do: 'A flat, straight option linking Plaza Saltillo toward the lake.',
    tip: null,
    transit: 'Plaza Saltillo (CapMetro Rail)',
  },
  {
    src: 'main-mall-path',
    id: 'ut-main-mall',
    name: 'UT Main Mall',
    category: 'path',
    score: 4,
    blurb: 'The ceremonial heart of the University of Texas campus.',
    see: 'The UT Tower above the fountains and live oaks, with the South Mall framing the Capitol view.',
    do: 'Run the Mall, then loop the campus and down to Waller Creek.',
    tip: null,
    transit: 'MLK Jr (CapMetro Rail)',
  },

  // ---- Parks, viewpoints & landmarks ----
  {
    src: 'auditorium-shores-at-town-lake-metropoli',
    id: 'auditorium-shores',
    name: 'Auditorium Shores',
    category: 'park',
    score: 5,
    blurb: 'The open lakefront lawn with the best downtown skyline view in Austin.',
    see: 'The full skyline across the water, the Stevie Ray Vaughan statue, and a big off-leash dog field.',
    do: 'A natural start/finish for the lake loop; catch the bats from the nearby Congress bridge at dusk.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
    endpoint: true,
  },
  {
    src: 'doug-sahm-hill',
    id: 'doug-sahm-hill',
    name: 'Doug Sahm Hill',
    category: 'viewpoint',
    score: 4,
    blurb: 'A gentle grassy summit in Butler Park overlooking the lake.',
    see: 'A 360° view of the skyline, the lake, and the Hill Country rolling off to the west.',
    do: 'A short, punchy climb just off the lake trail for the best free overlook downtown.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
    endpoint: true,
  },
  {
    src: 'lou-neff-point',
    id: 'lou-neff-point',
    name: 'Lou Neff Point',
    category: 'viewpoint',
    score: 4,
    blurb: 'A scenic lookout where Barton Creek meets Lady Bird Lake.',
    see: 'A little gazebo, the lake opening toward the skyline, and Zilker Park spreading behind.',
    do: 'A pretty turn on the lake loop and the gateway to Barton Springs.',
    tip: null,
    transit: 'Zilker Park (CapMetro bus)',
  },
  {
    src: 'capitol-mall',
    id: 'texas-capitol',
    name: 'Texas State Capitol Grounds',
    category: 'landmark',
    score: 5,
    blurb: 'The grounds of the towering pink-granite Texas Capitol.',
    see: 'The dome rising above live oaks and monuments, taller than the U.S. Capitol in Washington.',
    do: 'Run the Capitol grounds, then take the Congress Avenue axis down toward the lake.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
    endpoint: true,
  },
  {
    src: 'willie-nelson-statue',
    id: 'willie-nelson-statue',
    name: 'Willie Nelson Statue',
    category: 'landmark',
    score: 4,
    blurb: 'A bronze of Austin’s patron saint of country music, downtown.',
    see: 'Willie and his guitar Trigger outside ACL Live, on the street named for him.',
    do: 'A quick photo stop in the 2nd Street District.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'republic-square',
    id: 'republic-square',
    name: 'Republic Square',
    category: 'park',
    score: 3,
    blurb: 'A historic downtown square shaded by sprawling heritage oaks.',
    see: 'The “Auction Oaks” where Austin’s lots were first sold, ringed by farmers-market stalls on weekends.',
    do: null,
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'brush-square',
    id: 'brush-square',
    name: 'Brush Square',
    category: 'park',
    score: 3,
    blurb: 'A leafy downtown square preserving two of Austin’s oldest houses.',
    see: 'The O. Henry and Susanna Dickinson museum cottages under the trees.',
    do: null,
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'kingsbury-commons',
    id: 'kingsbury-commons-pease-park',
    name: 'Kingsbury Commons at Pease Park',
    category: 'park',
    score: 3,
    blurb: 'The revitalized lower end of Pease Park along Shoal Creek.',
    see: 'Restored lawns, a treehouse and splash play area, and the creek under big oaks.',
    do: 'A green anchor on the Shoal Creek Trail.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'texas-state-cemetery',
    id: 'texas-state-cemetery',
    name: 'Texas State Cemetery',
    category: 'park',
    score: 3,
    blurb: 'A quiet, history-steeped cemetery in East Austin.',
    see: 'The graves of Stephen F. Austin and Texas statesmen, with a reflecting pond and live oaks.',
    do: 'A calm, contemplative loop off the East Austin trails.',
    tip: null,
    transit: 'Plaza Saltillo (CapMetro Rail)',
  },
  {
    src: 'seaholm-waterfront-park-and-table',
    id: 'seaholm-waterfront',
    name: 'Seaholm Waterfront',
    category: 'park',
    score: 3,
    blurb: 'A reclaimed lakefront beside the old Seaholm power plant.',
    see: 'The restored Art Deco power station, new plazas, and the lake trail running past.',
    do: 'A modern downtown link between the library, the lake, and Shoal Creek.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'the-color-inside',
    id: 'the-color-inside',
    name: 'The Color Inside (Turrell Skyspace)',
    category: 'landmark',
    score: 3,
    blurb: 'A James Turrell skyspace crowning the UT student center.',
    see: 'An open oculus to the sky framed by shifting light — best at sunset.',
    do: 'A rooftop art detour on a campus run.',
    tip: 'Free, but the sunset light sequence is worth timing your run around.',
    transit: 'MLK Jr (CapMetro Rail)',
  },
  {
    src: 'angelina-eberly',
    id: 'angelina-eberly-statue',
    name: 'Angelina Eberly Statue',
    category: 'landmark',
    score: 3,
    blurb: 'A lively bronze of the woman who fired a cannon to keep Austin the capital.',
    see: 'Angelina mid-blast at the cannon she used in the 1842 “Archive War,” on Congress Avenue.',
    do: 'A fun downtown photo stop on the Congress Avenue axis.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'country-club-creek-trail-path',
    id: 'country-club-creek-trail',
    name: 'Country Club Creek Trail',
    category: 'path',
    score: 3,
    blurb: 'A creekside greenway through the fast-changing east side.',
    see: 'Quiet creek banks and neighborhood greenery linking toward the lake’s southeast shore.',
    do: 'Use it to extend the lake loop into East Riverside.',
    tip: null,
    transit: 'Plaza Saltillo (CapMetro Rail)',
  },
  {
    src: 'woodland-trail-path',
    id: 'woodland-trail',
    name: 'Woodland Trail',
    category: 'waterfront',
    score: 3,
    blurb: 'A wooded connector off the south shore of Lady Bird Lake.',
    see: 'Shaded creek and woodland just back from the lake near the Norwood estate.',
    do: 'A leafy spur off the south side of the Butler trail.',
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
  {
    src: 'hirshfeld-house',
    id: 'hirshfeld-house',
    name: 'Hirshfeld House',
    category: 'landmark',
    score: 2,
    blurb: 'An ornate Victorian home from Austin’s early downtown days.',
    see: 'Gingerbread trim and a wrought-iron fence on a leafy block west of Congress.',
    do: null,
    tip: null,
    transit: 'Downtown Station (CapMetro Rail)',
  },
]);
