// Chicago curation spec — see ../curate-lib.mjs. `src` ids come from out/chicago.json.
import { curate } from '../curate-lib.mjs';

curate('chicago', [
  // ---- Lakefront, river & rail-trail corridors ----
  {
    src: 'lakefront-trail-path',
    id: 'lakefront-trail',
    name: 'Lakefront Trail',
    category: 'waterfront',
    score: 5,
    blurb: 'Chicago’s legendary path along the Lake Michigan shore — 18 miles of open water and skyline.',
    see: 'The skyline stacked against the lake, beaches and harbors, and sailboats out on the blue.',
    do: 'Run the separated pedestrian lane north past the beaches or south to the Museum Campus.',
    tip: 'Separated run and bike paths most of the way; the lake wind can flip your effort on the return.',
    transit: 'Roosevelt (Red, Orange, Green)',
    endpoint: true,
  },
  {
    src: 'chicago-riverwalk-path',
    id: 'chicago-riverwalk',
    name: 'Chicago Riverwalk',
    category: 'waterfront',
    score: 5,
    blurb: 'A continuous promenade down at the water on the main branch of the Chicago River.',
    see: 'The river’s movable bridges overhead, the Marina City “corncobs,” and tour boats gliding past architecture.',
    do: 'Run the full Riverwalk from the lake to Lake Street, dipping under each bridge.',
    tip: 'Floods to the rail in high water; lively with bars and boats on summer evenings.',
    transit: 'State/Lake (Loop lines)',
    endpoint: true,
  },
  {
    src: 'bloomingdale-trail-path',
    id: 'the-606-bloomingdale-trail',
    name: 'The 606 (Bloomingdale Trail)',
    category: 'path',
    score: 5,
    blurb: 'An elevated rail-trail park running through the northwest-side neighborhoods.',
    see: 'Prairie plantings and art along an old freight line, with rooftop-level views over Wicker Park and Humboldt Park.',
    do: 'Run the full 2.7-mile viaduct end to end, above the street grid the whole way.',
    tip: 'Car-free and flat — a rare uninterrupted stretch away from the lake.',
    transit: 'Western (Blue)',
    endpoint: true,
  },
  {
    src: 'lincoln-park-fitness-course-path',
    id: 'lincoln-park-paths',
    name: 'Lincoln Park Paths',
    category: 'park',
    score: 4,
    blurb: 'Winding paths through the city’s largest lakefront park.',
    see: 'Lily ponds and the free zoo, the conservatory, and the skyline framed across South Pond.',
    do: 'Loop the park’s ponds and lawns, then drop onto the Lakefront Trail alongside.',
    tip: null,
    transit: 'Fullerton (Red, Brown, Purple)',
    endpoint: true,
  },
  {
    src: 'navy-pier-flyover-path',
    id: 'navy-pier-flyover',
    name: 'Navy Pier Flyover',
    category: 'waterfront',
    score: 4,
    blurb: 'An elevated section of the Lakefront Trail bypassing the Navy Pier crowds.',
    see: 'Bird’s-eye views over the river mouth, Ogden Slip, and the lake from the raised deck.',
    do: 'Use it to run the lakefront straight past Navy Pier without the foot traffic.',
    tip: null,
    transit: 'Grand (Red)',
  },
  {
    src: 'museum-campus-access-path-path',
    id: 'museum-campus',
    name: 'Museum Campus',
    category: 'park',
    score: 4,
    blurb: 'A lakefront park ringing Chicago’s trio of grand museums.',
    see: 'The Field Museum, Shedd Aquarium, and Adler Planetarium, with a postcard skyline view from the planetarium point.',
    do: 'Run out to the Adler’s lakefront point for the best skyline-and-water photo in the city.',
    tip: null,
    transit: 'Roosevelt (Red, Orange, Green)',
    endpoint: true,
  },
  {
    src: 'dearborn-street-bikeway-path',
    id: 'dearborn-street-bikeway',
    name: 'Dearborn Street Bikeway',
    category: 'path',
    score: 3,
    blurb: 'A protected two-way path straight through the Loop.',
    see: 'The Picasso sculpture at Daley Plaza, the County Building, and the Loop’s canyon of towers.',
    do: 'A direct north–south spine across downtown linking the river to Printers Row.',
    tip: null,
    transit: 'Washington (Blue)',
  },
  {
    src: 'milwaukee-avenue-bikeway-path',
    id: 'milwaukee-avenue-bikeway',
    name: 'Milwaukee Avenue Bikeway',
    category: 'path',
    score: 3,
    blurb: 'The diagonal artery through the hip near-northwest side.',
    see: 'Murals, taquerias, and vintage storefronts running from the river out to Wicker Park.',
    do: 'A street-level link from downtown toward the 606.',
    tip: null,
    transit: 'Damen (Blue)',
  },
  {
    src: 'riverwalk-path',
    id: 'ping-tom-riverwalk',
    name: 'Ping Tom Park Riverwalk',
    category: 'waterfront',
    score: 4,
    blurb: 'A riverside park and walk on the South Branch in Chinatown.',
    see: 'A red pavilion and pagoda-style bridge, willow banks, and the river curving toward downtown.',
    do: 'A quieter riverside loop south of the Loop.',
    tip: null,
    transit: 'Cermak-Chinatown (Red)',
  },

  // ---- Parks, plazas & viewpoints ----
  {
    src: 'millennium-park',
    id: 'millennium-park',
    name: 'Millennium Park',
    category: 'park',
    score: 5,
    blurb: 'Chicago’s showpiece park, home to “The Bean.”',
    see: 'Cloud Gate’s mirrored curve, the Pritzker Pavilion’s steel ribbons, and the faces of Crown Fountain.',
    do: 'Loop the park and cross the snaking BP Bridge into Maggie Daley Park next door.',
    tip: 'Mobbed at the Bean by day; run through at dawn to have the mirror to yourself.',
    transit: 'Washington/Wabash (Brown, Green, Orange, Pink, Purple)',
    endpoint: true,
  },
  {
    src: '360-chicago',
    id: '360-chicago',
    name: '360 Chicago (Hancock)',
    category: 'viewpoint',
    score: 5,
    blurb: 'The observation deck near the top of the former John Hancock Center.',
    see: 'The lake, the skyline, and four states on a clear day — plus the stomach-dropping TILT windows.',
    do: 'A landmark finish on a Magnificent Mile run.',
    tip: 'Ticketed and indoors; a destination rather than a running stop.',
    transit: 'Chicago (Red)',
  },
  {
    src: 'polk-bros-park',
    id: 'polk-bros-park-navy-pier',
    name: 'Navy Pier (Polk Bros Park)',
    category: 'park',
    score: 4,
    blurb: 'The gateway park at the foot of Navy Pier on the lakefront.',
    see: 'The pier’s Centennial Wheel, a performing fountain, and the lake opening east past the breakwater.',
    do: 'Run out along the pier for open-water views, then rejoin the Lakefront Trail.',
    tip: null,
    transit: 'Grand (Red)',
    endpoint: true,
  },
  {
    src: 'the-willis-terrace',
    id: 'willis-tower-wacker',
    name: 'Willis Tower & Wacker',
    category: 'landmark',
    score: 4,
    blurb: 'The foot of the tower that was North America’s tallest for a generation.',
    see: 'The black-steel Willis (Sears) Tower soaring overhead, with the river and Wacker Drive alongside.',
    do: 'A Loop landmark linking the Riverwalk to the Dearborn bikeway.',
    tip: null,
    transit: 'Quincy (Brown, Orange, Pink, Purple)',
  },
  {
    src: 'jane-m-byrne-plaza',
    id: 'water-tower-byrne-plaza',
    name: 'Water Tower & Byrne Plaza',
    category: 'landmark',
    score: 3,
    blurb: 'The limestone Water Tower that survived the Great Chicago Fire.',
    see: 'The castellated 1869 tower marooned among the Magnificent Mile’s high-rises, with a plaza alongside.',
    do: 'A historic waypoint on a Michigan Avenue run.',
    tip: null,
    transit: 'Chicago (Red)',
  },
  {
    src: 'south-garden',
    id: 'art-institute-south-garden',
    name: 'Art Institute South Garden',
    category: 'park',
    score: 3,
    blurb: 'A sunken garden room beside the Art Institute on Michigan Avenue.',
    see: 'A Hedge of honey locusts around the Fountain of the Great Lakes, walled off from the street noise.',
    do: 'A shaded pause between Millennium Park and the museum’s bronze lions.',
    tip: null,
    transit: 'Adams/Wabash (Brown, Green, Orange, Pink, Purple)',
  },
  {
    src: 'pritzker-park',
    id: 'pritzker-park',
    name: 'Pritzker Park',
    category: 'park',
    score: 2,
    blurb: 'A small Loop park across from the Harold Washington Library.',
    see: 'Trees and seating inspired by a Magritte painting, tucked into the South Loop edge.',
    do: null,
    tip: null,
    transit: 'Library (Brown, Orange, Pink, Purple)',
  },
  {
    src: 'printers-row-park',
    id: 'printers-row-park',
    name: 'Printers Row Park',
    category: 'park',
    score: 2,
    blurb: 'A slender triangle park in the historic Printers Row district.',
    see: 'The landmark Dearborn Station clock tower closing the view down the street.',
    do: null,
    tip: null,
    transit: 'LaSalle (Blue)',
  },
  {
    src: 'haymarket-memorial',
    id: 'haymarket-memorial',
    name: 'Haymarket Memorial',
    category: 'landmark',
    score: 3,
    blurb: 'A monument marking the site of the 1886 Haymarket Affair.',
    see: 'A bronze sculpture on a speaker’s-wagon plinth where the rally for the eight-hour day turned tragic.',
    do: 'A labor-history stop on a West Loop / river run.',
    tip: null,
    transit: 'Clinton (Green, Pink)',
  },
  {
    src: 'chicago-city-hall-roof-garden',
    id: 'city-hall-roof-garden',
    name: 'Chicago City Hall Roof Garden',
    category: 'landmark',
    score: 2,
    blurb: 'One of the city’s pioneering green roofs, atop City Hall in the Loop.',
    see: 'A planted prairie roof (glimpsed from neighboring towers) that helped launch Chicago’s green-roof movement.',
    do: 'A landmark to note in passing through the Loop — the roof itself is not open to the public.',
    tip: null,
    transit: 'Washington (Blue)',
  },
  {
    src: 'grandmother-s-garden',
    id: 'grandmothers-garden',
    name: 'Grandmother’s Garden',
    category: 'park',
    score: 3,
    blurb: 'A historic perennial garden in north Lincoln Park.',
    see: 'Informal beds of native perennials, one of the oldest public gardens in the city, by the Lincoln statue.',
    do: 'A pretty turnaround on a north Lincoln Park run.',
    tip: null,
    transit: 'Fullerton (Red, Brown, Purple)',
  },
  {
    src: 'lincoln-gardens',
    id: 'lincoln-park-conservatory-gardens',
    name: 'Lincoln Park Conservatory Gardens',
    category: 'park',
    score: 3,
    blurb: 'Formal gardens beside the Victorian glasshouse in Lincoln Park.',
    see: 'A grand Beaux-Arts garden, the conservatory’s glass domes, and seasonal flower shows.',
    do: 'Pair with the zoo and pond paths on a Lincoln Park loop.',
    tip: null,
    transit: 'Fullerton (Red, Brown, Purple)',
  },
  {
    src: 'american-writers-museum',
    id: 'american-writers-museum',
    name: 'American Writers Museum',
    category: 'landmark',
    score: 2,
    blurb: 'A museum of American literature on Michigan Avenue.',
    see: 'Interactive galleries celebrating the nation’s writers, across from Millennium Park.',
    do: null,
    tip: null,
    transit: 'Washington/Wabash (Brown, Green, Orange, Pink, Purple)',
  },
]);
