// London curation spec — see ../curate-lib.mjs. `src` ids come from out/london.json.
import { curate } from '../curate-lib.mjs';

curate('london', [
  // ---- Thames & canal corridors ----
  {
    src: 'victoria-embankment-path',
    id: 'victoria-embankment',
    name: 'Victoria Embankment',
    category: 'waterfront',
    score: 5,
    blurb: 'A grand riverside boulevard along the north bank of the Thames.',
    see: 'Cleopatra’s Needle, the sphinxes and dolphin lamps, and the London Eye turning across the water.',
    do: 'Run west toward Westminster and Big Ben or east to the City and Blackfriars.',
    tip: 'A continuous, traffic-separated riverside path — one of central London’s best straight runs.',
    transit: 'Embankment (Circle, District, Northern)',
    endpoint: true,
  },
  {
    src: 'the-queen-s-walk-path',
    id: 'south-bank-queens-walk',
    name: 'The Queen’s Walk (South Bank)',
    category: 'waterfront',
    score: 5,
    blurb: 'The buzzing South Bank riverside promenade facing the City skyline.',
    see: 'The London Eye, the Royal Festival Hall, skateboarders at the Undercroft, and St Paul’s across the river.',
    do: 'Follow it from Westminster Bridge past the Tate Modern toward Tower Bridge.',
    tip: 'Packed with strollers midday; run it early or push the pace at dawn.',
    transit: 'Waterloo (Bakerloo, Jubilee, Northern)',
    endpoint: true,
  },
  {
    src: 'regent-s-canal-towpath-path',
    id: 'regents-canal-towpath',
    name: 'Regent’s Canal Towpath',
    category: 'waterfront',
    score: 5,
    blurb: 'A quiet canalside towpath threading north London below street level.',
    see: 'Narrowboats and locks, the leafy edge of Regent’s Park, and the villas of Little Venice.',
    do: 'Run west to Little Venice or east toward Camden Lock and the markets.',
    tip: 'Narrow and shared with cyclists — keep left and mind the blind bridge holes.',
    transit: 'Warwick Avenue (Bakerloo)',
    endpoint: true,
  },
  {
    src: 'chelsea-embankment-path',
    id: 'chelsea-embankment',
    name: 'Chelsea Embankment',
    category: 'waterfront',
    score: 4,
    blurb: 'A handsome Thames-side stretch past the gardens of Chelsea.',
    see: 'The red suspension cables of Albert Bridge, houseboats moored at Cheyne Walk, and plane trees along the river.',
    do: 'Connect to Battersea Park across the bridge or run on toward Pimlico.',
    tip: null,
    transit: 'Sloane Square (Circle, District)',
  },
  {
    src: 'bazalgette-embankment-path',
    id: 'thames-path-st-pauls',
    name: 'Thames Path at Millennium Bridge',
    category: 'waterfront',
    score: 4,
    blurb: 'The City riverside walk beneath the dome of St Paul’s.',
    see: 'St Paul’s Cathedral above the north bank and the slender Millennium Bridge spanning to the Tate Modern.',
    do: 'Cross the Millennium Bridge to link the City with the South Bank.',
    tip: null,
    transit: 'Mansion House (Circle, District)',
  },

  // ---- Royal park walks ----
  {
    src: 'the-mall-path',
    id: 'the-mall',
    name: 'The Mall',
    category: 'path',
    score: 5,
    blurb: 'The ceremonial red avenue sweeping up to Buckingham Palace.',
    see: 'The Victoria Memorial and palace gates at one end, Admiralty Arch and Trafalgar Square at the other.',
    do: 'Run the processional route, then loop into St James’s Park alongside.',
    tip: 'Closed to traffic on Sundays — the smoothest ceremonial mile in the city.',
    transit: 'Charing Cross (Bakerloo, Northern)',
    endpoint: true,
  },
  {
    src: 'west-carriage-drive-path',
    id: 'serpentine-hyde-park',
    name: 'The Serpentine, Hyde Park',
    category: 'waterfront',
    score: 5,
    blurb: 'The lake at the heart of Hyde Park, ringed by a popular running loop.',
    see: 'Rowing boats and swimmers on the water, the Diana Memorial fountain, and open parkland in every direction.',
    do: 'Circle the lake, then strike out across the park on Rotten Row or the Broad Walk.',
    tip: 'The full Serpentine loop is a classic ~2 mile circuit; join the dawn swimmers for a cold dip.',
    transit: 'Lancaster Gate (Central)',
    endpoint: true,
  },
  {
    src: 'rotten-row-path',
    id: 'rotten-row',
    name: 'Rotten Row, Hyde Park',
    category: 'path',
    score: 4,
    blurb: 'A broad sand horse-riding track running the length of Hyde Park.',
    see: 'Riders exercising their horses, the Albert Memorial’s gilded spire, and long avenues of trees.',
    do: 'A soft-surface alternative to the pavements; links Hyde Park Corner to Kensington.',
    tip: null,
    transit: 'Hyde Park Corner (Piccadilly)',
  },
  {
    src: 'the-broadwalk-path',
    id: 'kensington-gardens-broad-walk',
    name: 'Kensington Gardens Broad Walk',
    category: 'park',
    score: 4,
    blurb: 'A wide tree-lined promenade through the calmer western half of the royal parks.',
    see: 'Kensington Palace, the Round Pond with its model boats, and the Italian Gardens fountains.',
    do: 'Run from the palace down to the Serpentine to join Hyde Park.',
    tip: null,
    transit: 'Queensway (Central)',
  },
  {
    src: 'the-broad-walk-path',
    id: 'regents-park-broad-walk',
    name: 'Regent’s Park Broad Walk',
    category: 'park',
    score: 5,
    blurb: 'The grand central avenue of Regent’s Park, lined with formal gardens.',
    see: 'The Avenue Gardens’ fountains and urns, the dome of the central mosque, and the heights of Primrose Hill beyond.',
    do: 'Run the Broad Walk then take on the short, sharp climb of Primrose Hill for the skyline view.',
    tip: null,
    transit: 'Regent’s Park (Bakerloo)',
    endpoint: true,
  },

  // ---- City icons & viewpoints ----
  {
    src: 'tower-bridge',
    id: 'tower-bridge',
    name: 'Tower Bridge',
    category: 'viewpoint',
    score: 5,
    blurb: 'The Victorian bascule bridge whose twin towers are a symbol of the city.',
    see: 'The blue-and-white drawbridge, the Tower of London on the bank, and the Pool of London opening downstream.',
    do: 'Cross the river here to link the South Bank with the City and St Katharine Docks.',
    tip: 'Check the bridge-lift times posted online — the road deck opens for tall ships.',
    transit: 'Tower Hill (Circle, District)',
    endpoint: true,
  },
  {
    src: 'sky-garden',
    id: 'sky-garden',
    name: 'Sky Garden',
    category: 'viewpoint',
    score: 5,
    blurb: 'A free public garden under glass atop the “Walkie-Talkie” tower.',
    see: 'A 360° panorama over the Thames, the Shard, and the City from 35 floors up.',
    do: 'A destination viewpoint to bookend a City run — book the free timed entry ahead.',
    tip: 'Indoors and ticketed (free); a finish-line reward rather than a running stop.',
    transit: 'Monument (Circle, District)',
  },
  {
    src: 'the-garden-at-120',
    id: 'garden-at-120',
    name: 'The Garden at 120',
    category: 'viewpoint',
    score: 4,
    blurb: 'A free rooftop garden terrace in the heart of the City.',
    see: 'Close-up views of the Gherkin, the Leadenhall “Cheesegrater,” and the cluster of City towers.',
    do: 'A quick lift up for a skyline breather on a City loop.',
    tip: null,
    transit: 'Bank (Central, Northern)',
  },

  // ---- Garden squares & historic greens ----
  {
    src: 'victoria-embankment-gardens',
    id: 'victoria-embankment-gardens',
    name: 'Victoria Embankment Gardens',
    category: 'park',
    score: 4,
    blurb: 'A ribbon of riverside gardens tucked behind the Embankment.',
    see: 'Bandstand lawns, statues, and flowerbeds a step back from the Thames traffic.',
    do: 'A shaded, flat connector between Embankment and the river path.',
    tip: null,
    transit: 'Embankment (Circle, District, Northern)',
  },
  {
    src: 'victoria-tower-gardens',
    id: 'victoria-tower-gardens',
    name: 'Victoria Tower Gardens',
    category: 'park',
    score: 4,
    blurb: 'A riverside park right beside the Houses of Parliament.',
    see: 'The Victoria Tower of Parliament, Rodin’s Burghers of Calais, and the river curving toward Lambeth Bridge.',
    do: 'A green pause directly under Westminster on a Thames-side run.',
    tip: null,
    transit: 'Westminster (Circle, District, Jubilee)',
  },
  {
    src: 'russell-square',
    id: 'russell-square',
    name: 'Russell Square',
    category: 'park',
    score: 4,
    blurb: 'One of Bloomsbury’s largest and leafiest garden squares.',
    see: 'A central fountain, mature planes, and the terracotta façade of the Hotel Russell.',
    do: 'A calm lap in the museum quarter, steps from the British Museum.',
    tip: null,
    transit: 'Russell Square (Piccadilly)',
  },
  {
    src: 'queen-square-gardens',
    id: 'queen-square-gardens',
    name: 'Queen Square Gardens',
    category: 'park',
    score: 3,
    blurb: 'A small, quiet Bloomsbury square among the hospitals and old houses.',
    see: 'Shaded benches, a statue of Queen Charlotte, and ivy-clad Georgian terraces.',
    do: null,
    tip: null,
    transit: 'Russell Square (Piccadilly)',
  },
  {
    src: 'brunswick-square-gardens',
    id: 'brunswick-square-gardens',
    name: 'Brunswick Square Gardens',
    category: 'park',
    score: 3,
    blurb: 'A leafy Bloomsbury square beside the Foundling Museum.',
    see: 'One of London’s oldest plane trees and lawns shared with the neighbouring Coram’s Fields.',
    do: null,
    tip: null,
    transit: 'Russell Square (Piccadilly)',
  },
  {
    src: 'lincoln-s-inn',
    id: 'lincolns-inn',
    name: 'Lincoln’s Inn',
    category: 'park',
    score: 4,
    blurb: 'The grounds of one of the four historic Inns of Court.',
    see: 'Tudor brick gatehouses, the chapel, and lawns backing onto Lincoln’s Inn Fields, London’s largest square.',
    do: 'Thread the quiet legal quarter between Holborn and the Royal Courts of Justice.',
    tip: 'The Inn’s private gates close in the evening; the adjoining Fields stay open.',
    transit: 'Holborn (Central, Piccadilly)',
  },
  {
    src: 'gray-s-inn-gardens',
    id: 'grays-inn-gardens',
    name: 'Gray’s Inn Gardens',
    category: 'park',
    score: 3,
    blurb: 'The serene private gardens (“The Walks”) of Gray’s Inn.',
    see: 'Long lawns and ancient plane trees said to have been planted by Francis Bacon.',
    do: null,
    tip: 'Open to the public only on weekday lunchtimes.',
    transit: 'Chancery Lane (Central)',
  },
  {
    src: 'middle-temple-garden',
    id: 'middle-temple-garden',
    name: 'Middle Temple Garden',
    category: 'park',
    score: 3,
    blurb: 'A riverside lawn within the medieval Temple, between Fleet Street and the Thames.',
    see: 'Tudor halls, the round Temple Church, and a garden tied in legend to the Wars of the Roses.',
    do: 'A hidden green detour off the Victoria Embankment.',
    tip: null,
    transit: 'Temple (Circle, District)',
  },
  {
    src: 'mount-street-gardens',
    id: 'mount-street-gardens',
    name: 'Mount Street Gardens',
    category: 'park',
    score: 3,
    blurb: 'A sheltered, sun-trap garden hidden in the heart of Mayfair.',
    see: 'London plane and Australian mimosa trees, songbirds, and rows of memorial benches.',
    do: 'A quiet breather amid Mayfair’s grand streets.',
    tip: null,
    transit: 'Bond Street (Central, Jubilee)',
  },
  {
    src: 'phoenix-garden',
    id: 'phoenix-garden',
    name: 'Phoenix Garden',
    category: 'park',
    score: 3,
    blurb: 'A small community wildlife garden steps from the West End theatres.',
    see: 'Cottage planting, a pond, and the city’s only central-London frogs, behind Soho’s bustle.',
    do: null,
    tip: null,
    transit: 'Tottenham Court Road (Central, Northern)',
  },
  {
    src: 'chelsea-physic-garden',
    id: 'chelsea-physic-garden',
    name: 'Chelsea Physic Garden',
    category: 'park',
    score: 3,
    blurb: 'London’s oldest botanic garden, walled beside the river in Chelsea.',
    see: 'Rare medicinal plants, glasshouses, and Britain’s largest outdoor fruiting olive tree.',
    do: 'A walled-garden landmark just off the Chelsea Embankment.',
    tip: 'Ticketed and gated — a passing landmark rather than a through-route.',
    transit: 'Sloane Square (Circle, District)',
  },
  {
    src: 'red-cross-garden',
    id: 'red-cross-garden',
    name: 'Red Cross Garden',
    category: 'park',
    score: 3,
    blurb: 'A restored Victorian “open-air sitting room” in Southwark.',
    see: 'A bandstand, pond, and cottage gardens laid out by social reformer Octavia Hill.',
    do: 'A green pause near Borough Market on a South Bank loop.',
    tip: null,
    transit: 'Borough (Northern)',
  },
  {
    src: 'st-pancras-gardens',
    id: 'st-pancras-gardens',
    name: 'St Pancras Old Church & Gardens',
    category: 'park',
    score: 3,
    blurb: 'A churchyard garden behind the stations, one of London’s oldest sites of worship.',
    see: 'The ancient church, Sir John Soane’s tomb, and the Hardy Tree ringed by gravestones.',
    do: 'A quiet detour from the Regent’s Canal towpath nearby.',
    tip: null,
    transit: 'King’s Cross St Pancras (Northern, Victoria, Piccadilly)',
  },
  {
    src: 'fortune-street-park',
    id: 'fortune-street-park',
    name: 'Fortune Street Park',
    category: 'park',
    score: 2,
    blurb: 'A neighbourhood green on the edge of the Barbican and the City.',
    see: 'Lawns and ball courts hemmed in by the Barbican’s concrete towers.',
    do: 'A handy turnaround on a City fringe run toward the Barbican.',
    tip: null,
    transit: 'Barbican (Circle, Metropolitan)',
  },
  {
    src: 'leicester-square',
    id: 'leicester-square',
    name: 'Leicester Square',
    category: 'neighborhood',
    score: 3,
    blurb: 'The West End’s film-premiere square, ringed by cinemas and crowds.',
    see: 'The Shakespeare fountain, movie-star handprints, and the bright lights of the theatre district.',
    do: 'A central crossroads between Soho, Covent Garden, and Trafalgar Square.',
    tip: 'Heaving with crowds day and night — pass through, don’t linger.',
    transit: 'Leicester Square (Northern, Piccadilly)',
  },
]);
