// Miami curation spec — see ../curate-lib.mjs. `src` ids come from out/miami.json.
import { curate } from '../curate-lib.mjs';

curate('miami', [
  // ---- Bay, beach & causeway corridors ----
  {
    src: 'rickenbacker-trail-path',
    id: 'rickenbacker-causeway-trail',
    name: 'Rickenbacker Causeway Trail',
    category: 'waterfront',
    score: 5,
    blurb: 'The wide bayside path arcing across the water toward Key Biscayne.',
    see: 'Open Biscayne Bay, the downtown skyline behind you, sailboarders, and the rise of the William Powell Bridge.',
    do: 'Run out over the bridge for the skyline view, with Hobie Beach and Virginia Key beyond.',
    tip: 'Exposed and windy with no shade — go early and carry water; the bridge is the one real hill in Miami.',
    transit: 'Brickell (Metrorail)',
    endpoint: true,
  },
  {
    src: 'baywalk-path',
    id: 'brickell-baywalk',
    name: 'Brickell Bay Walk',
    category: 'waterfront',
    score: 5,
    blurb: 'A baywalk threading between Brickell’s glass towers and the water.',
    see: 'Biscayne Bay, luxury high-rises, and yachts moored along the seawall.',
    do: 'Connect north to the Miami River and downtown’s Bayfront Park.',
    tip: 'A few private-property gaps still break the path; detour a block inland where it ends.',
    transit: 'Brickell (Metromover)',
    endpoint: true,
  },
  {
    src: 'lummus-park-boardwalk-path',
    id: 'south-beach-beachwalk',
    name: 'South Beach Beachwalk (Lummus Park)',
    category: 'waterfront',
    score: 5,
    blurb: 'The beachfront promenade along the sand of South Beach.',
    see: 'Pastel Art Deco hotels on Ocean Drive, palm groves, lifeguard towers, and the Atlantic surf.',
    do: 'Run the beachwalk past the Deco District and on toward South Pointe.',
    tip: null,
    transit: 'South Beach (bus 120)',
    endpoint: true,
  },
  {
    src: 'mid-beach-boardwalk-path',
    id: 'miami-beach-boardwalk',
    name: 'Miami Beach Boardwalk',
    category: 'waterfront',
    score: 5,
    blurb: 'A continuous beachfront boardwalk running up the Mid-Beach dunes.',
    see: 'Sea-grape and dune plantings, grand oceanfront hotels, and uninterrupted Atlantic views.',
    do: 'A long, flat, car-free stretch — ideal for tempo miles north from South Beach.',
    tip: null,
    transit: 'Mid-Beach (bus 120)',
    endpoint: true,
  },
  {
    src: 'south-pointe-park-walk-path',
    id: 'south-pointe-park-walk',
    name: 'South Pointe Park',
    category: 'waterfront',
    score: 5,
    blurb: 'The green southern tip of Miami Beach where the bay meets the ocean.',
    see: 'Cruise ships sliding through Government Cut, the South Pointe Pier, and skyline views across the water.',
    do: 'Loop the park paths and run the pier out over the channel.',
    tip: null,
    transit: 'South Pointe (bus)',
    endpoint: true,
  },
  {
    src: 'macarthur-causeway-path-path',
    id: 'macarthur-causeway-baywalk',
    name: 'MacArthur Causeway Baywalk',
    category: 'waterfront',
    score: 4,
    blurb: 'The bayside path along the main causeway between downtown and South Beach.',
    see: 'The Port of Miami’s cruise terminals, the mansions of Star Island, and the bay on both sides.',
    do: 'A long water crossing linking the mainland to Miami Beach.',
    tip: 'Traffic-side and exposed — best as a point-to-point, not a there-and-back.',
    transit: 'Museum Park (Metromover)',
  },
  {
    src: 'virginia-key-north-point-trails-path',
    id: 'virginia-key-trails',
    name: 'Virginia Key North Point Trails',
    category: 'path',
    score: 4,
    blurb: 'Sandy nature and mountain-bike trails on a barrier island off the causeway.',
    see: 'Mangroves, hammock forest, quiet beaches, and skyline glimpses across the bay.',
    do: 'Trade pavement for soft singletrack just minutes from downtown.',
    tip: null,
    transit: 'Brickell (Metrorail)',
  },
  {
    src: 'riverwalk-path',
    id: 'miami-riverwalk',
    name: 'Miami Riverwalk',
    category: 'waterfront',
    score: 4,
    blurb: 'A downtown promenade along the historic Miami River.',
    see: 'Working fishing boats and drawbridges, riverside restaurants, and the towers of the financial district.',
    do: 'Trace the river inland from the bay to link Brickell and downtown.',
    tip: null,
    transit: 'Brickell (Metromover)',
  },
  {
    src: 'commodore-trail-path',
    id: 'commodore-trail',
    name: 'Commodore Trail',
    category: 'path',
    score: 3,
    blurb: 'A shaded path running south toward leafy Coconut Grove.',
    see: 'Banyan canopies, bayfront estates, and the village edge of the Grove.',
    do: 'Head south to Vizcaya and the Grove’s marinas.',
    tip: null,
    transit: 'Vizcaya (Metrorail)',
  },

  // ---- Parks, gardens & landmarks ----
  {
    src: 'vizcaya-museum-and-gardens',
    id: 'vizcaya-museum-and-gardens',
    name: 'Vizcaya Museum and Gardens',
    category: 'park',
    score: 5,
    blurb: 'A Gilded-Age Italian villa and formal gardens on the edge of the bay.',
    see: 'Baroque fountains and clipped hedges, the stone barge breakwater, and the villa above Biscayne Bay.',
    do: 'A landmark turnaround at the south end of a bayfront run.',
    tip: 'Gardens are ticketed; a passing landmark unless you stop in.',
    transit: 'Vizcaya (Metrorail)',
  },
  {
    src: 'south-pointe-park-pier',
    id: 'south-pointe-park-pier',
    name: 'South Pointe Park Pier',
    category: 'viewpoint',
    score: 5,
    blurb: 'A curving pier at the southern tip of Miami Beach.',
    see: 'Cruise ships and freighters threading Government Cut, with the skyline and Fisher Island across the water.',
    do: 'Run the pier as the turnaround on a South Beach loop.',
    tip: null,
    transit: 'South Pointe (bus)',
    endpoint: true,
  },
  {
    src: 'maurice-a-ferr-park',
    id: 'maurice-ferre-park',
    name: 'Maurice A. Ferré Park (Museum Park)',
    category: 'park',
    score: 4,
    blurb: 'A waterfront park downtown framing two of Miami’s signature museums.',
    see: 'The Pérez Art Museum’s hanging gardens, the domed Frost science museum, and the bay beyond.',
    do: 'A green anchor between the downtown baywalk and the causeways.',
    tip: null,
    transit: 'Museum Park (Metromover)',
  },
  {
    src: 'the-underline',
    id: 'the-underline',
    name: 'The Underline',
    category: 'park',
    score: 4,
    blurb: 'A linear park and path unfurling beneath the Metrorail tracks.',
    see: 'Native gardens, murals, and public art running south from Brickell along the transit line.',
    do: 'A shaded, car-free spine connecting Brickell toward Coconut Grove.',
    tip: null,
    transit: 'Brickell (Metrorail)',
  },
  {
    src: 'miami-circle-at-brickell-point',
    id: 'miami-circle',
    name: 'Miami Circle at Brickell Point',
    category: 'landmark',
    score: 3,
    blurb: 'A prehistoric Tequesta site carved in the bedrock at the river mouth.',
    see: 'The circular archaeological ring on a small bayfront lawn where the Miami River meets the bay.',
    do: 'A quick history stop at the start of the Brickell baywalk.',
    tip: null,
    transit: 'Brickell (Metromover)',
  },
  {
    src: 'jose-marti-riverfront-park',
    id: 'jose-marti-park',
    name: 'José Martí Park',
    category: 'park',
    score: 3,
    blurb: 'A riverfront park at the gateway to Little Havana.',
    see: 'Royal palms and a riverside walk where downtown meets the Cuban-American heart of the city.',
    do: 'Pick up the Miami Riverwalk here heading toward the bay.',
    tip: null,
    transit: 'Brickell (Metromover)',
  },
  {
    src: 'belle-isle-park',
    id: 'belle-isle-park',
    name: 'Belle Isle Park',
    category: 'park',
    score: 3,
    blurb: 'A small island park at the foot of the Venetian Causeway.',
    see: 'A baywalk circling the island with open views back to the Miami Beach skyline.',
    do: 'Loop the island as a quiet detour off the Venetian Causeway run.',
    tip: null,
    transit: 'South Beach (bus)',
  },
  {
    src: 'collins-park',
    id: 'collins-park',
    name: 'Collins Park',
    category: 'park',
    score: 3,
    blurb: 'A cultural green in South Beach beside the Bass Museum.',
    see: 'Sculpture on the lawn, the Bass contemporary-art museum, and the library, a block from the sand.',
    do: null,
    tip: null,
    transit: 'Mid-Beach (bus 120)',
  },
  {
    src: 'miami-beach-botanical-garden',
    id: 'miami-beach-botanical-garden',
    name: 'Miami Beach Botanical Garden',
    category: 'park',
    score: 3,
    blurb: 'A lush pocket garden in the heart of Miami Beach.',
    see: 'Palms, orchids, and a lily pond with the Convention Center alongside.',
    do: null,
    tip: null,
    transit: 'Mid-Beach (bus 120)',
  },
  {
    src: 'ichimura-miami-japanese-garden',
    id: 'ichimura-japanese-garden',
    name: 'Ichimura Miami-Japan Garden',
    category: 'park',
    score: 3,
    blurb: 'A serene Japanese garden on Watson Island in the bay.',
    see: 'Koi ponds, stone lanterns, and raked gravel framed by downtown towers across the water.',
    do: 'A calm detour off the MacArthur Causeway.',
    tip: null,
    transit: 'Museum Park (Metromover)',
  },
  {
    src: 'alice-c-wainwright-park',
    id: 'alice-wainwright-park',
    name: 'Alice Wainwright Park',
    category: 'park',
    score: 3,
    blurb: 'A bayfront park on the rise toward Coconut Grove.',
    see: 'Hardwood hammock, a rare ridge of limestone, and open bay views toward Key Biscayne.',
    do: 'A green waypoint on the Commodore Trail south of Brickell.',
    tip: null,
    transit: 'Vizcaya (Metrorail)',
  },
  {
    src: 'maurice-gibb-memorial-park',
    id: 'maurice-gibb-park',
    name: 'Maurice Gibb Memorial Park',
    category: 'park',
    score: 2,
    blurb: 'A small waterfront park on the Sunset Harbour bayfront.',
    see: 'A short baywalk and dock with views over the marina and the Venetian islands.',
    do: null,
    tip: null,
    transit: 'South Beach (bus)',
  },
]);
