// Paris curation spec — see ../curate-lib.mjs. `src` ids come from out/paris.json.
import { curate } from '../curate-lib.mjs';

curate('paris', [
  // ---- Seine & greenway corridors ----
  {
    src: 'all-e-des-cygnes-path',
    id: 'allee-des-cygnes',
    name: 'Allée des Cygnes',
    category: 'waterfront',
    score: 5,
    blurb: 'A slender tree-lined island in the middle of the Seine, made for running.',
    see: 'The Seine on both sides, the Pont de Bir-Hakeim overhead, and a quarter-scale Statue of Liberty at the downstream tip.',
    do: 'Run the full length of the islet and circle the little Liberty before doubling back.',
    tip: 'Car-free and flat; one of the most peaceful stretches of riverside in the city.',
    transit: 'Bir-Hakeim (6)',
    endpoint: true,
  },
  {
    src: 'terrasse-du-bord-de-l-eau-path',
    id: 'tuileries-riverside',
    name: 'Tuileries Riverside Terrace',
    category: 'waterfront',
    score: 5,
    blurb: 'The raised Seine-side terrace running the length of the Jardin des Tuileries.',
    see: 'Gravel allées and clipped chestnuts on one side, the river and the Musée d’Orsay across the water on the other.',
    do: 'Link west to the Place de la Concorde or east under the Louvre arches.',
    tip: 'The garden gates close at night; run it by day for the full Louvre-to-Concorde sweep.',
    transit: 'Tuileries (1)',
    endpoint: true,
  },
  {
    src: 'promenade-du-quai-branly-path',
    id: 'quai-branly-riverside',
    name: 'Quai Branly Riverside',
    category: 'waterfront',
    score: 5,
    blurb: 'Left-bank Seine promenade running straight beneath the Eiffel Tower.',
    see: 'The Tower rising directly above, bateaux-mouches on the river, and the gardens of the Quai Branly museum.',
    do: 'Continue to the Champ de Mars or cross the Pont de l’Alma to the Right Bank.',
    tip: 'Busy with tourists by midday near the Tower; go early for clear running.',
    transit: 'Pont de l’Alma (RER C)',
    endpoint: true,
  },
  {
    src: 'esplanade-david-ben-gourion-path',
    id: 'trocadero-gardens',
    name: 'Jardins du Trocadéro',
    category: 'waterfront',
    score: 4,
    blurb: 'Cascading fountains and lawns sloping down to the Seine opposite the Eiffel Tower.',
    see: 'The grand fountain basin, the Palais de Chaillot wings, and the postcard Tower view across the river.',
    do: 'Climb the steps to the Trocadéro esplanade for the classic photo line.',
    tip: null,
    transit: 'Trocadéro (6, 9)',
  },
  {
    src: 'coul-e-verte-ren-dumont-path',
    id: 'coulee-verte-rene-dumont',
    name: 'Coulée verte René-Dumont',
    category: 'path',
    score: 5,
    blurb: 'An elevated planted greenway atop a former railway viaduct — the inspiration for New York’s High Line.',
    see: 'Rose arbours and grasses running above the 12th arrondissement, with rooftop-level views over Bastille.',
    do: 'Run it east toward the Bois de Vincennes or descend to the Viaduc des Arts arcades below.',
    tip: 'Narrow in places; ease off the pace where it threads between buildings.',
    transit: 'Bastille (1, 5, 8)',
    endpoint: true,
  },
  {
    src: 'route-circulaire-du-lac-path',
    id: 'buttes-chaumont-lake-loop',
    name: 'Parc des Buttes-Chaumont Lake Loop',
    category: 'park',
    score: 5,
    blurb: 'A dramatic hilly park built on old quarries, with a cliff-island temple in a lake.',
    see: 'The suspension footbridge, the Temple de la Sibylle on its crag, and waterfalls tumbling into the lake.',
    do: 'Loop the lake then take on the steep climbs the park is loved (and feared) for.',
    tip: 'The hills here are the real thing — a proper interval workout in the northeast of the city.',
    transit: 'Buttes Chaumont (7bis)',
    endpoint: true,
  },
  {
    src: 'all-e-buffon-path',
    id: 'jardin-des-plantes',
    name: 'Jardin des Plantes',
    category: 'park',
    score: 4,
    blurb: 'The city’s historic botanical garden, laid out in long formal allées.',
    see: 'Perspective rows of plane trees, the Natural History galleries, and a small menagerie zoo.',
    do: 'Run the central allée end to end, then loop out along the Seine quais nearby.',
    tip: null,
    transit: 'Gare d’Austerlitz (5, 10)',
  },

  // ---- Viewpoints & icons ----
  {
    src: 'esplanade-du-trocad-ro',
    id: 'place-du-trocadero',
    name: 'Place du Trocadéro',
    category: 'viewpoint',
    score: 5,
    blurb: 'The great esplanade between the Palais de Chaillot wings — the best Eiffel Tower view in Paris.',
    see: 'The full Tower framed across the Seine, with the fountains stepping down toward the river below.',
    do: 'Pause for the view, then drop down through the gardens to the riverside.',
    tip: 'Arrive at sunrise for the Tower light and empty pavements.',
    transit: 'Trocadéro (6, 9)',
    endpoint: true,
  },
  {
    src: 'montmartre',
    id: 'montmartre-sacre-coeur',
    name: 'Montmartre & Sacré-Cœur',
    category: 'viewpoint',
    score: 5,
    blurb: 'The hilltop village crowned by the white domes of the Sacré-Cœur basilica.',
    see: 'All of Paris spread below from the basilica steps, plus the artists’ square of Place du Tertre behind.',
    do: 'Grind up the stairways and lanes, then wind down the quiet north side of the butte.',
    tip: 'It’s the highest point in the city — expect a real climb and crowded steps up top.',
    transit: 'Anvers (2)',
    endpoint: true,
  },
  {
    src: 'toit-de-l-arc-de-triomphe',
    id: 'arc-de-triomphe',
    name: 'Arc de Triomphe',
    category: 'viewpoint',
    score: 5,
    blurb: 'Napoleon’s triumphal arch at the hub of twelve radiating avenues.',
    see: 'The Champs-Élysées sweeping down toward the Louvre and, the other way, La Défense on the horizon.',
    do: 'Circle the Étoile via the pedestrian underpass, never the traffic ring.',
    tip: 'Use the underpass to reach the arch — the roundabout is one of the busiest in Europe.',
    transit: 'Charles de Gaulle–Étoile (1, 2, 6)',
  },
  {
    src: 'notre-dame',
    id: 'notre-dame-ile-de-la-cite',
    name: 'Notre-Dame & Île de la Cité',
    category: 'landmark',
    score: 5,
    blurb: 'The Gothic cathedral at the very heart of Paris, on the island where the city began.',
    see: 'The restored spire and flying buttresses, the Seine wrapping the island, and the booksellers’ green boxes along the quais.',
    do: 'Loop the island on the riverside quais for cathedral views from every angle.',
    tip: null,
    transit: 'Cité (4)',
    endpoint: true,
  },
  {
    src: 'pont-des-arts',
    id: 'pont-des-arts',
    name: 'Pont des Arts',
    category: 'viewpoint',
    score: 4,
    blurb: 'The wooden pedestrian bridge linking the Louvre to the Institut de France.',
    see: 'A clean sightline down the Seine to the Île de la Cité, with the Louvre on one bank and the Académie dome on the other.',
    do: 'Cross between the Right and Left Banks here on a riverside loop.',
    tip: null,
    transit: 'Louvre–Rivoli (1)',
  },
  {
    src: 'square-du-vert-galant',
    id: 'square-du-vert-galant',
    name: 'Square du Vert-Galant',
    category: 'park',
    score: 4,
    blurb: 'A leafy little park at the downstream prow of the Île de la Cité, right at water level.',
    see: 'The Seine splitting around the island’s point and the arches of the Pont Neuf overhead.',
    do: 'Drop down the steps from the Pont Neuf for a quiet riverside breather.',
    tip: 'Floods after heavy rain; closed when the river runs high.',
    transit: 'Pont Neuf (7)',
  },

  // ---- Gardens & squares ----
  {
    src: 'jardin-du-palais-royal',
    id: 'jardin-du-palais-royal',
    name: 'Jardin du Palais-Royal',
    category: 'park',
    score: 4,
    blurb: 'A serene arcaded garden hidden behind the former royal palace.',
    see: 'Symmetrical lime-tree avenues, fountains, and Buren’s striped columns in the forecourt.',
    do: 'A calm, flat lap moments from the Louvre — good for an easy warm-up.',
    tip: null,
    transit: 'Palais Royal–Musée du Louvre (1, 7)',
  },
  {
    src: 'place-du-carrousel',
    id: 'louvre-carrousel',
    name: 'Louvre & Jardin du Carrousel',
    category: 'landmark',
    score: 5,
    blurb: 'The palace courtyards and gardens linking the Louvre to the Tuileries.',
    see: 'I. M. Pei’s glass pyramid, the pink Arc du Carrousel, and the grand axis stretching to the Concorde obelisk.',
    do: 'Run the historic axis from the pyramid out through the Tuileries.',
    tip: null,
    transit: 'Palais Royal–Musée du Louvre (1, 7)',
    endpoint: true,
  },
  {
    src: 'palais-garnier',
    id: 'palais-garnier',
    name: 'Palais Garnier (Opéra)',
    category: 'landmark',
    score: 4,
    blurb: 'The opulent 19th-century opera house that gave the Phantom its setting.',
    see: 'A gilded, statue-crowned façade closing the view up the Avenue de l’Opéra.',
    do: 'Use it as a turnaround on a Right Bank loop through the grands boulevards.',
    tip: null,
    transit: 'Opéra (3, 7, 8)',
  },
  {
    src: 'conciergerie',
    id: 'conciergerie',
    name: 'Conciergerie',
    category: 'landmark',
    score: 4,
    blurb: 'A medieval royal palace turned Revolutionary prison on the Île de la Cité.',
    see: 'Round defensive towers along the Seine and the city’s oldest public clock on the corner.',
    do: 'Pass it on a riverside loop of the island toward Notre-Dame.',
    tip: null,
    transit: 'Cité (4)',
  },
  {
    src: 'square-de-la-tour-saint-jacques',
    id: 'tour-saint-jacques',
    name: 'Square de la Tour Saint-Jacques',
    category: 'park',
    score: 3,
    blurb: 'A small garden around a lone flamboyant-Gothic tower near Châtelet.',
    see: 'The lacy stone tower — all that remains of a vanished church — rising over the flowerbeds.',
    do: null,
    tip: null,
    transit: 'Châtelet (1, 4, 7, 11, 14)',
  },
  {
    src: 'square-marie-trintignant',
    id: 'square-marie-trintignant',
    name: 'Square Marie-Trintignant',
    category: 'park',
    score: 3,
    blurb: 'A riverside garden on the Right Bank quays at the edge of the Marais.',
    see: 'The Seine and the tip of the Île Saint-Louis just across the water.',
    do: 'Connect along the quais toward the Île Saint-Louis bridges.',
    tip: null,
    transit: 'Pont Marie (7)',
  },
  {
    src: 'jardin-nelson-mandela',
    id: 'jardin-nelson-mandela',
    name: 'Jardin Nelson-Mandela (Les Halles)',
    category: 'park',
    score: 3,
    blurb: 'The big central garden above the Forum des Halles, on the old market site.',
    see: 'Open lawns and play areas under the rippling glass Canopée roof, with Saint-Eustache church alongside.',
    do: 'A flat green crossroads linking the Louvre, the Marais, and the river.',
    tip: null,
    transit: 'Les Halles (RER A)',
  },
  {
    src: 'jardin-de-kyiv',
    id: 'jardin-de-kyiv',
    name: 'Jardin de Kyiv',
    category: 'park',
    score: 2,
    blurb: 'A quiet terraced garden behind the Place de la Concorde gardens.',
    see: 'Hedged walks a short hop from the Tuileries and the Madeleine.',
    do: null,
    tip: null,
    transit: 'Concorde (1, 8, 12)',
  },
  {
    src: 'mus-e-des-arts-et-m-tiers',
    id: 'arts-et-metiers',
    name: 'Musée des Arts et Métiers',
    category: 'landmark',
    score: 3,
    blurb: 'A science-and-industry museum in a former priory at the edge of the Marais.',
    see: 'Foucault’s pendulum and early flying machines inside; a steampunk-tiled métro station below.',
    do: 'A landmark turn on a northern Marais loop.',
    tip: null,
    transit: 'Arts et Métiers (3, 11)',
  },
  {
    src: 'brasserie-bofinger',
    id: 'place-de-la-bastille',
    name: 'Bastille',
    category: 'neighborhood',
    score: 3,
    blurb: 'The lively square where the Revolution began, now a hub of cafés and nightlife.',
    see: 'The bronze July Column with its gilded spirit of Liberty at the centre of the roundabout.',
    do: 'Start the Coulée verte greenway here, or head to the Marais and the river.',
    tip: null,
    transit: 'Bastille (1, 5, 8)',
  },
  {
    src: 'promenade-d-australie-path',
    id: 'promenade-d-australie',
    name: 'Promenade d’Australie',
    category: 'waterfront',
    score: 4,
    blurb: 'A right-bank riverside walk below the Passy hill, opposite the Allée des Cygnes.',
    see: 'The Seine, the Pont de Bir-Hakeim’s iron deck, and the Eiffel Tower downstream.',
    do: 'Drop onto the Allée des Cygnes island midstream from the bridge.',
    tip: null,
    transit: 'Passy (6)',
  },
  {
    src: 'square-jean-xxiii',
    id: 'square-jean-xxiii',
    name: 'Square Jean-XXIII',
    category: 'park',
    score: 3,
    blurb: 'The garden directly behind Notre-Dame, along the tip of the Île de la Cité.',
    see: 'The cathedral’s east end and flying buttresses rising straight above the rose beds.',
    do: 'Best vantage on Notre-Dame’s spire; pair it with an island riverside loop.',
    tip: null,
    transit: 'Cité (4)',
  },
  {
    src: 'jardin-des-combattants-de-la-nueve',
    id: 'hotel-de-ville',
    name: 'Hôtel de Ville',
    category: 'neighborhood',
    score: 3,
    blurb: 'The grand neo-Renaissance city hall facing a wide riverside plaza.',
    see: 'An ornate statue-lined façade and the open square that turns into an ice rink each winter.',
    do: 'A natural Right Bank waypoint between the Marais and the Île de la Cité.',
    tip: null,
    transit: 'Hôtel de Ville (1, 11)',
  },
  {
    src: 'mus-e-de-la-l-gion-d-honneur-et-des-ordr',
    id: 'musee-legion-d-honneur',
    name: 'Musée de la Légion d’Honneur',
    category: 'landmark',
    score: 3,
    blurb: 'An elegant mansion museum on the Left Bank beside the Musée d’Orsay.',
    see: 'The Hôtel de Salm’s rotunda and, next door, Orsay’s great clock-faced railway hall.',
    do: 'Cut to the Seine here and pick up the Left Bank quais.',
    tip: null,
    transit: 'Solférino (12)',
  },
  {
    src: 'jardin-sauvage-saint-vincent',
    id: 'montmartre-vineyard',
    name: 'Clos Montmartre & Jardin Saint-Vincent',
    category: 'park',
    score: 3,
    blurb: 'Paris’s last working vineyard, tucked into the quiet north slope of Montmartre.',
    see: 'Terraced vines, the pink Au Lapin Agile cabaret, and steep village lanes with no crowds.',
    do: 'Loop the calm back side of the butte away from the Sacré-Cœur tourist crush.',
    tip: null,
    transit: 'Lamarck–Caulaincourt (12)',
  },
]);
